import type { Metadata } from "next";
import { Geist, Geist_Mono, Stack_Sans_Text } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const stackSans = Stack_Sans_Text({
  variable: "--font-stack-sans",
  subsets: ["latin"]
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${stackSans.variable} h-full antialiased bg-(--bg-primary) text-(--text-primary)`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        </body>
    </html>
  );
}
